### ISSUE TITLE
Exponentiating `log_var` twice in NLL function of `GaussianNoiseModel`

### ISSUE THREAD

**Issue by h-spiess** [phlippe/ENCO#1]
Hey,

I know you haven't applied your model to continuous data, but we have used the `GaussianNoiseModel` in one of our projects.

At
https://github.com/phlippe/ENCO/blob/38168401930db66f42f65cb77a7ccefa19095a46/causal_discovery/multivariable_flow.py#L258
you exponentiate the third argument, which is already exponentiated in 
https://github.com/phlippe/ENCO/blob/d3318cb692370e1804806c21207266905d9e0e47/causal_discovery/multivariable_flow.py#L25-L26

This leads to `y[..., 1]` being exponentiated twice, which we think shouldn't.

Best,
Heiner

**Comment by phlippe** [comment]
Hi Heiner, thanks a lot for pointing this out! This is indeed a bug, which probably makes it a bit harder for the model to learn. It should be fixed with the newest commit. 
Best,
Phillip

**Comment by h-spiess** [comment]
Hey Phillip, thanks for addressing it that quickly. We found it because it led to `NaN`s in the Bidiagonal graph type, where already large log variances were twice exponentiated.
Best, 
Heiner
