### ISSUE TITLE
convergence_guarantees_ENCO

### ISSUE THREAD

**Issue by NamelessGod008** [phlippe/ENCO#2]
sorry to bother,
but did u remove the file named 'convergence_guarantees_ENCO.ipynb'? 
it's mentioned in the paper but cannot be found.

**Comment by phlippe** [comment]
Hi, thanks for pointing it out. We had created the notebook after releasing the initial public code. I have added it now in the commit 70292442ae8aca5fc3902ba86dff7ea091fcca89. Let me know if you have any questions.
