### ISSUE TITLE
Missing SID metric

### ISSUE THREAD

**Issue by Onedean** [phlippe/ENCO#3]
Hi, Phillip

Nice Work! But I didn't find the implementation of SID metric in your code, can you add it?
I found it in another R package, but it seems that the implementation is not good.
Thank you so much!

Best,
Wei.

**Comment by phlippe** [comment]
Hi Wei,

Very sorry for the long response delay, I somehow missed the issue notification.
For the SID metric, we used this function: https://fentechsolutions.github.io/CausalDiscoveryToolbox/html/metrics.html#cdt.metrics.SID. This code is a wrapper around R-code which implements it, which might be similar to the one you were looking into. Unfortunately, we didn't find a good, pure-python implementation we could share here.
