### ISSUE TITLE
How to generate/create the interventions

### ISSUE THREAD

**Issue by SaqibMamoon** [phlippe/ENCO#4]
Dear Authors, 
Thank you for sharing complete and comprehensive code of the article. I have some questions.
1) I want to apply this model on the fMRI data, so I only have observational data/graph (num_time * num_var), and don't have interventional data.
2) Can I run this model without interventional data or how could I generate the interventions on this kind of data.

Thanks a lot. 
Warmest Regards,

**Comment by phlippe** [comment]
Hi there,

Our method is specifically designed for scenarios where interventional data is available. While it can be applied to observational data to a certain degree, I would instead recommend taking a look at methods that specifically focus on observational data, e.g. the [PC algorithm](https://cran.r-project.org/web/packages/pcalg/index.html), [FCI](https://cran.r-project.org/web/packages/pcalg/index.html), or [NOTEARS](https://github.com/xunzheng/notears).
